name: "CD -> Artifact"
on:
  workflow_dispatch:
  push:
    branches:
      - stable

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.repository_owner == 'jspaste' }}
    name: "Build artifact"
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write

    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: "Setup Bun"
        uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1.2.1

      - name: "Release tag"
        id: release-tag
        run: echo "id=$(date +%Y.%m.%d)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: "Checkout"
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: "Setup dependencies"
        run: bun install --production --frozen-lockfile

      - name: "Build artifact"
        run: |
          bun run build:standalone:darwin-arm64
          tar -czf ./dist/backend_${{ steps.release-tag.outputs.id }}_darwin_arm64.tar.gz LICENSE README.md -C ./dist/ backend

          bun run build:standalone:linux-arm64
          tar -czf ./dist/backend_${{ steps.release-tag.outputs.id }}_linux_arm64.tar.gz LICENSE README.md -C ./dist/ backend

          bun run build:standalone:linux-x64
          tar -czf ./dist/backend_${{ steps.release-tag.outputs.id }}_linux_x64.tar.gz LICENSE README.md -C ./dist/ backend

          bun run build:standalone:windows-x64
          zip -j -X ./dist/backend_${{ steps.release-tag.outputs.id }}_windows_x64.zip LICENSE README.md ./dist/backend

      - name: "Sign artifact (.tar.gz)"
        uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940 # v1.0.0
        with:
          subject-path: 'dist/*.tar.gz'

      - name: "Sign artifact (.zip)"
        uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940 # v1.0.0
        with:
          subject-path: 'dist/*.zip'

      - name: "Release artifact"
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          name: ${{ steps.release-tag.outputs.id }}
          tag: ${{ steps.release-tag.outputs.id }}
          artifacts: "dist/*.tar.gz,dist/*.zip"
          makeLatest: true
          generateReleaseNotes: true
