---
name: CD
on:
  workflow_dispatch:
    inputs:
      artifact-action:
        description: Artifact action
        type: choice
        required: true
        default: none
        options:
          - none
          - build
          - build-release
      image-action:
        description: Container image action
        type: choice
        required: true
        default: none
        options:
          - none
          - build
          - build-release

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  artifact:
    if: github.repository_owner == 'jspaste' && inputs.artifact-action != 'none'
    name: Release artifact
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: "audit"

      - name: Setup mise-en-place
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Save context
        id: ctx
        env:
          CTX_BRANCH: "${{ github.head_ref || github.ref_name }}"
          CTX_SHA: "${{ github.event.pull_request.head.sha || github.sha }}"
        run: |
          echo "branch=${CTX_BRANCH}" >>"$GITHUB_OUTPUT"
          echo "sha=${CTX_SHA}" >>"$GITHUB_OUTPUT"
          echo "sha_short=${CTX_SHA::7}" >>"$GITHUB_OUTPUT"

      - name: Save tags
        id: tags
        env:
          BRANCH: "${{ steps.ctx.outputs.branch }}"
          SHA_SHORT: "${{ steps.ctx.outputs.sha_short }}"
        run: |
          TIMESTAMP="$(date +%Y.%m.%d)"

          if [[ "${BRANCH}" == "stable" ]]; then
            TAG="latest"
          else
            TAG="snapshot"
          fi

          echo "tag=${TAG}" >>"$GITHUB_OUTPUT"
          echo "extended=${TIMESTAMP}-${SHA_SHORT}" >>"$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: "false"

      - name: Build artifact
        run: |
          mise run build:standalone:darwin-arm64
          chmod 755 ./dist/backend.darwin-arm64
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ backend.darwin-arm64 | xz -z -6 >./dist/backend-${{ steps.tags.outputs.tag }}_darwin-arm64.tar.xz
          tar -tJf ./dist/backend-${{ steps.tags.outputs.tag }}_darwin-arm64.tar.xz >/dev/null

          mise run build:standalone:linux-amd64
          chmod 755 ./dist/backend.linux-amd64
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ backend.linux-amd64 | xz -z -6 >./dist/backend-${{ steps.tags.outputs.tag }}_linux-amd64.tar.xz
          tar -tJf ./dist/backend-${{ steps.tags.outputs.tag }}_linux-amd64.tar.xz >/dev/null

          mise run build:standalone:linux-arm64
          chmod 755 ./dist/backend.linux-arm64
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ backend.linux-arm64 | xz -z -6 >./dist/backend-${{ steps.tags.outputs.tag }}_linux-arm64.tar.xz
          tar -tJf ./dist/backend-${{ steps.tags.outputs.tag }}_linux-arm64.tar.xz >/dev/null

          mise run build:standalone:windows-amd64
          chmod 755 ./dist/backend.windows-amd64.exe
          zip -j -X -9 -l -o ./dist/backend-${{ steps.tags.outputs.tag }}_windows-amd64.zip .env.example LICENSE README.md ./dist/backend.windows-amd64.exe
          zip -T ./dist/backend-${{ steps.tags.outputs.tag }}_windows-amd64.zip

          # FIXME: Deno still doesn't expose arm64 target
          #mise run build:standalone:windows-arm64
          #chmod 755 ./dist/backend.windows-arm64.exe
          #zip -j -X -9 -l -o ./dist/backend-${{ steps.tags.outputs.tag }}_windows-arm64.zip .env.example LICENSE README.md ./dist/backend.windows-arm64.exe
          #zip -T ./dist/backend-${{ steps.tags.outputs.tag }}_windows-arm64.zip

      - if: inputs.artifact-action == 'build-release'
        name: Release artifact
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          name: "${{ steps.tags.outputs.extended }}"
          tag: "${{ steps.tags.outputs.extended }}"
          artifacts: "dist/*.tar.xz,dist/*.zip"
          makeLatest: "true"
          prerelease: "${{ steps.ctx.outputs.branch != 'stable' }}"
          generateReleaseNotes: "${{ steps.ctx.outputs.branch == 'stable' }}"

      - if: inputs.artifact-action == 'build-release'
        name: Attest artifact
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: |
            dist/*.tar.xz
            dist/*.zip

  container:
    if: github.repository_owner == 'jspaste' && inputs.image-action != 'none'
    name: Release container image
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write
      packages: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: "audit"

      - name: Setup mise-en-place
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: Setup podman
        env:
          PODMAN_VERSION: "v5.8.2"
        run: |
          sudo apt-get purge -y podman runc crun conmon

          curl -fsSLO "https://github.com/mgoltzsche/podman-static/releases/download/${{ env.PODMAN_VERSION }}/podman-linux-amd64.tar.gz"
          curl -fsSLO "https://github.com/mgoltzsche/podman-static/releases/download/${{ env.PODMAN_VERSION }}/podman-linux-amd64.tar.gz.asc"
          gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0CCF102C4F95D89E583FF1D4F8B5AF50344BB503
          gpg --batch --verify "podman-linux-amd64.tar.gz.asc" "podman-linux-amd64.tar.gz"

          tar -xzf "podman-linux-amd64.tar.gz"
          sudo cp -rfv ./podman-linux-amd64/etc/. /etc/
          sudo cp -rfv ./podman-linux-amd64/usr/. /usr/

          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - if: inputs.image-action == 'build-release'
        name: Login to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: "ghcr.io"

      - if: inputs.image-action == 'build-release'
        name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: "${{ secrets.DOCKER_USER }}"
          password: "${{ secrets.DOCKER_TOKEN }}"
          registry: "docker.io"

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: "false"

      - name: Build container image
        run: |
          if [ "${{ inputs.image-action }}" = "build-release" ]; then
            mise run build:container --release
          else
            mise run build:container
          fi