---
name: CD
on:
  workflow_dispatch:
    inputs:
      artifact-action:
        description: Artifact action
        type: choice
        required: true
        default: none
        options:
          - none
          - build
          - build-release
      image-action:
        description: Container image action
        type: choice
        required: true
        default: none
        options:
          - none
          - build
          - build-release

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  artifact:
    if: github.repository_owner == 'jspaste' && inputs.artifact-action != 'none'
    name: Release artifact
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: "audit"

      - name: Setup mise-en-place
        uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

      - name: Save context
        id: ctx
        env:
          CTX_BRANCH: "${{ github.head_ref || github.ref_name }}"
          CTX_SHA: "${{ github.event.pull_request.head.sha || github.sha }}"
        run: |
          echo "branch=${CTX_BRANCH}" >>"$GITHUB_OUTPUT"
          echo "sha=${CTX_SHA}" >>"$GITHUB_OUTPUT"
          echo "sha_short=${CTX_SHA::7}" >>"$GITHUB_OUTPUT"

      - name: Save tags
        id: tags
        env:
          BRANCH: "${{ steps.ctx.outputs.branch }}"
          SHA_SHORT: "${{ steps.ctx.outputs.sha_short }}"
        run: |
          TIMESTAMP="$(date +%Y.%m.%d)"

          if [[ "${BRANCH}" == "stable" ]]; then
            TAG="latest"
          else
            TAG="snapshot"
          fi

          echo "tag=${TAG}" >>"$GITHUB_OUTPUT"
          echo "extended=${TIMESTAMP}-${SHA_SHORT}" >>"$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: "false"

      - name: Build artifact
        run: |
          mise run build:standalone:darwin-arm64
          chmod 755 ./dist/backend.darwin-arm64
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ backend.darwin-arm64 | xz -z -6 >./dist/backend-${{ steps.tags.outputs.tag }}_darwin-arm64.tar.xz
          tar -tJf ./dist/backend-${{ steps.tags.outputs.tag }}_darwin-arm64.tar.xz >/dev/null

          mise run build:standalone:linux-amd64
          chmod 755 ./dist/backend.linux-amd64
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ backend.linux-amd64 | xz -z -6 >./dist/backend-${{ steps.tags.outputs.tag }}_linux-amd64.tar.xz
          tar -tJf ./dist/backend-${{ steps.tags.outputs.tag }}_linux-amd64.tar.xz >/dev/null

          mise run build:standalone:linux-arm64
          chmod 755 ./dist/backend.linux-arm64
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ backend.linux-arm64 | xz -z -6 >./dist/backend-${{ steps.tags.outputs.tag }}_linux-arm64.tar.xz
          tar -tJf ./dist/backend-${{ steps.tags.outputs.tag }}_linux-arm64.tar.xz >/dev/null

          mise run build:standalone:windows-amd64
          chmod 755 ./dist/backend.windows-amd64.exe
          zip -j -X -9 -l -o ./dist/backend-${{ steps.tags.outputs.tag }}_windows-amd64.zip .env.example LICENSE README.md ./dist/backend.windows-amd64.exe
          zip -T ./dist/backend-${{ steps.tags.outputs.tag }}_windows-amd64.zip

      - if: inputs.artifact-action == 'build-release'
        name: Release artifact
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          name: "${{ steps.tags.outputs.extended }}"
          tag: "${{ steps.tags.outputs.extended }}"
          artifacts: "dist/*.tar.xz,dist/*.zip"
          makeLatest: "true"
          prerelease: "${{ steps.ctx.outputs.branch != 'stable' }}"
          generateReleaseNotes: "${{ steps.ctx.outputs.branch == 'stable' }}"

      - if: inputs.artifact-action == 'build-release'
        name: Attest artifact
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: |
            dist/*.tar.xz
            dist/*.zip

  container:
    if: github.repository_owner == 'jspaste' && inputs.image-action != 'none'
    name: Release container image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    permissions:
      attestations: write
      id-token: write
      packages: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: "audit"

      - name: Save context
        id: ctx
        env:
          CTX_BRANCH: "${{ github.head_ref || github.ref_name }}"
          CTX_SHA: "${{ github.event.pull_request.head.sha || github.sha }}"
        run: |
          echo "branch=${CTX_BRANCH}" >>"$GITHUB_OUTPUT"
          echo "sha=${CTX_SHA}" >>"$GITHUB_OUTPUT"
          echo "sha_short=${CTX_SHA::7}" >>"$GITHUB_OUTPUT"

      - name: Save tags
        id: tags
        env:
          BRANCH: "${{ steps.ctx.outputs.branch }}"
          SHA: "${{ steps.ctx.outputs.sha }}"
          SHA_SHORT: "${{ steps.ctx.outputs.sha_short }}"
        run: |
          TIMESTAMP="$(date +%Y.%m.%d)"
          TIMESTAMP_ISO="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

          if [[ "${BRANCH}" == "stable" ]]; then
            TAGS+=("latest")
          else
            TAGS+=("snapshot")
          fi

          TAGS+=("${SHA}")
          TAGS+=("${TIMESTAMP}-${SHA_SHORT}")

          echo "timestamp=${TIMESTAMP}" >>"$GITHUB_OUTPUT"
          echo "timestamp_iso=${TIMESTAMP_ISO}" >>"$GITHUB_OUTPUT"
          echo "version=${TIMESTAMP}-${SHA_SHORT}" >>"$GITHUB_OUTPUT"
          echo "list=${TAGS[*]}" >>"$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: "false"

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          containerfiles: "Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          image: "${{ github.repository }}"
          layers: "true"
          oci: "true"
          tags: "${{ steps.tags.outputs.list }}"
          extra-args: |
            --squash
            --identity-label=false
            --label=org.opencontainers.image.created=${{ steps.tags.outputs.timestamp_iso }}
            --label=org.opencontainers.image.revision=${{ steps.ctx.outputs.sha }}
            --label=org.opencontainers.image.version=${{ steps.tags.outputs.version }}

      - if: inputs.image-action == 'build-release'
        name: Login to GHCR
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: "${{ env.REGISTRY }}"

      - if: inputs.image-action == 'build-release'
        name: Push to GHCR
        id: push-image
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: "${{ steps.build-image.outputs.image }}"
          tags: "${{ steps.build-image.outputs.tags }}"
          registry: "${{ env.REGISTRY }}"

      - if: inputs.image-action == 'build-release'
        name: Attest image
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: "${{ env.REGISTRY }}/${{ steps.build-image.outputs.image }}"
          subject-digest: "${{ steps.push-image.outputs.digest }}"
          push-to-registry: "false"
