---
name: CI
on:
  merge_group:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.ctx.outputs.branch }}
      sha: ${{ steps.ctx.outputs.sha }}
      sha_short: ${{ steps.ctx.outputs.sha_short }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Save context information
        id: ctx
        env:
          CTX_BRANCH: ${{ github.head_ref || github.ref_name }}
          CTX_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          echo "branch=${CTX_BRANCH}" >>"$GITHUB_OUTPUT"
          echo "sha=${CTX_SHA}" >>"$GITHUB_OUTPUT"
          echo "sha_short=${CTX_SHA::7}" >>"$GITHUB_OUTPUT"

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Run lint
        run: bun run lint

      - name: Build server
        run: bun run build:server

      - name: Test run server
        run: |
          bun run start:server &
          SERVER_PID=$!
          sleep 10
          kill $SERVER_PID
