---
name: CI
on:
  merge_group:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.ctx.outputs.branch }}
      sha: ${{ steps.ctx.outputs.sha }}
      sha_short: ${{ steps.ctx.outputs.sha_short }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: "audit"

      - name: Save context information
        id: ctx
        env:
          CTX_BRANCH: "${{ github.head_ref || github.ref_name }}"
          CTX_SHA: "${{ github.event.pull_request.head.sha || github.sha }}"
        run: |
          echo "branch=${CTX_BRANCH}" >>"$GITHUB_OUTPUT"
          echo "sha=${CTX_SHA}" >>"$GITHUB_OUTPUT"
          echo "sha_short=${CTX_SHA::7}" >>"$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: "false"

      - name: Setup mise-en-place
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

      - name: Run lint
        run: mise run lint

      - name: Run tests
        run: mise run test

      - name: Build server
        run: mise run build

      - name: Run server
        run: |
          mise run start:server &
          SERVER_PID=$!
          sleep 5
          kill $SERVER_PID
