name: "CD -> Container"
on:
  workflow_dispatch:
  push:
    branches:
      - stable

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.repository_owner == 'jspaste' }}
    name: "Build container image"
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: "Setup QEMU"
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: "Setup tags"
        id: setup-tags
        run: |
          TIMESTAMP="$(date +%Y.%m.%d)"
          SHA_SHORT="${GITHUB_SHA::7}"

          TAGS=()
          TAGS+=("latest")
          TAGS+=("${GITHUB_SHA}")
          TAGS+=("${TIMESTAMP}-${SHA_SHORT}")

          echo "build-tags=${TAGS[*]}" >> $GITHUB_OUTPUT

      - name: "Build image"
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          archs: amd64, arm64
          containerfiles: Dockerfile
          image: ${{ github.repository }}
          layers: true
          oci: true
          tags: ${{ steps.setup-tags.outputs.build-tags }}

      - name: "Push to GHCR"
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
